default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wardrobe_development

test:
  <<: *default
  database: wardrobe_test

production:
  <<: *default
  database: wardrobe_production
  username: wardrobe
  password: <%= ENV["WARDROBE_DATABASE_PASSWORD"] %>
